daylight:
	python ../../tohtml.py  daylight.story 'Harry Moses:  How Daylight Was Stolen' > daylight.html
	open daylight.html

short:
	python ../../tohtml.py  daylight-short.story 'Harry Moses:  How Daylight Was Stolen' > daylight-short.html
	open daylight-short.html

piece:
	python ../../tohtml.py  pieceOfdaylightBrokenOff.story 'Harry Moses:  How Daylight Was Stolen' > pieceOfDaylight.html
	open pieceOfDaylight.html

