daylight:
	python ../../tohtml.py  daylight.story 'Harry Moses:  How Daylight Was Stolen' > daylight.html
	open daylight.html

piece:
	python ../../tohtml.py  pieceOfdaylightBrokenOff.story 'Harry Moses:  How Daylight Was Stolen' > pieceOfDaylight.html
	open pieceOfDaylight.html

